# Generated by Django 5.1.5 on 2025-06-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbinary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yahoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbinary.us')),
            ],
        ),
        migrations.CreateModel(
            name='Yahoo_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbinary.us')),
            ],
        ),
        migrations.CreateModel(
            name='Yahoo_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbinary.us')),
            ],
        ),
    ]
