# Generated by Django 5.1.5 on 2025-08-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbinary', '0005_cvupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvupload',
            old_name='user',
            new_name='us',
        ),
    ]
