# Generated by Django 5.2.7 on 2026-02-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbinary', '0006_rename_user_cvupload_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_enabled', models.BooleanField(default=False, verbose_name='Enable Apply')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbinary.us')),
            ],
        ),
    ]
